alias gst='git status'
alias gl='git pull'
alias gp='git push'
alias gd='git diff | mate'
alias gau='git add --update'
alias ga='git add .'
alias gcm='git commit -m'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gr='git remote -v'
alias gra='git remote add'
alias gb='git branch -v'
alias gba='git branch -a'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcot='git checkout -t'
alias gcotb='git checkout --track -b'
alias glog='git log'
alias glogp='git log --pretty=format:"%C(yellow)%h\\ %Creset%s%Cblue\\ [%cn]\\%Cred%d" --decorate'
alias grb='git rebase'
alias grbc='git rebase --continuel'

alias kc='kubectl'